sonar_node:
  ros__parameters:
    sonar_filter_window: 10

line_node:
  ros__parameters:
    line_threshold: 0.0295

robot_brain_node:
  ros__parameters:
    base_speed: 1.0
    turn_speed: 1.2
    safe_distance_m: 0.5
    alpha_v: 0.15
    alpha_w: 0.25